cmake_minimum_required(VERSION 3.22.1)
project(mcnpu)
add_library(mcnpu SHARED mcnpu.cpp)
set(QNN_INC "" CACHE PATH "QNN headers")
if(NOT QNN_INC)
    message(FATAL_ERROR "QNN_INC is required")
endif()
target_include_directories(mcnpu PRIVATE ${QNN_INC})
find_library(log-lib log)
target_link_libraries(mcnpu ${log-lib} dl)
target_compile_features(mcnpu PRIVATE cxx_std_17)
target_compile_options(mcnpu PRIVATE -fvisibility=hidden -ffunction-sections -fdata-sections -Wall -Wextra)
target_link_options(mcnpu PRIVATE -Wl,--gc-sections)
